build:
    environment:
        php: '8.0.19'

    tests:
        override:
            - true # disable test execution on scrutinizer

    dependencies:
        override:
            - true

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
